<?php

namespace Database\Seeders;

use App\Models\Site;
use Illuminate\Database\Seeder;

class SiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'id_site' => 'A01',
                'site' => 'Taman Anggrek Residence',
                'buss' => 'A',
                'id_corp' => 'AMA',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Barat',
                'address' => 'Jl. Tj. Duren Timur 2 No.12, RT.12/RW.1, Tj. Duren Sel., Kec. Grogol petamburan, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11470',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1804084,106.7918128&z=15&output=embed',
            ],
            [
                'id_site' => 'A02',
                'site' => 'Fatmawati City Center',
                'buss' => 'A',
                'id_corp' => 'KAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Selatan',
                'address' => 'Jl. Fatmawati Raya, RT.3/RW.9, Cilandak Bar., Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12430',
                'url_maps' => 'https://maps.google.com/maps?q=-6.292832,106.797974&z=14&output=embed',
            ],
            [
                'id_site' => 'A03',
                'site' => 'Menara Jakarta',
                'buss' => 'A',
                'id_corp' => 'PPP',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Arena Pekan Raya Jkt - Kemayoran, Jl. H. Benyamin Sueb No.10, RW.10, Gn. Sahari Sel., Kec. Kemayoran, Jkt Utara, Daerah Khusus Ibukota Jakarta 14410',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1498668,106.8464893&z=15&output=embed',
            ],
            [
                'id_site' => 'F01',
                'site' => 'FLIX PIK',
                'buss' => 'C',
                'id_corp' => 'SAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Pantai Indah Kapuk St Boulevard, RT.6/RW.2, Kamal Muara, Penjaringan, North Jakarta City, Jakarta 14470',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1100266,106.7394165&z=15&output=embed',
            ],
            [
                'id_site' => 'F02',
                'site' => 'FLIX MOI',
                'buss' => 'C',
                'id_corp' => 'SAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Jl. Boulevard Bar. Raya No.12, RT.18/RW.19, Klp. Gading Bar., Kec. Klp. Gading, Jkt Utara, Daerah Khusus Ibukota Jakarta 14240',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1514549,106.8918949&z=12&output=embed',
            ],
            [
                'id_site' => 'F03',
                'site' => 'FLIX GGP',
                'buss' => 'C',
                'id_corp' => 'SAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Bekasi Selatan',
                'address' => 'Jl. Boulevard Raya No.1, RT.003/RW.017, Jaka Setia, Kec. Bekasi Sel., Kota Bks, Jawa Barat 17147',
                'url_maps' => 'https://maps.google.com/maps?q=-6.2706285,106.9722969&z=15&output=embed',
            ],
            [
                'id_site' => 'F04',
                'site' => 'FLIX ASHTA',
                'buss' => 'C',
                'id_corp' => 'SAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Selatan',
                'address' => 'Jl. Senopati No.83, Senayan, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190',
                'url_maps' => 'https://maps.google.com/maps?q=-6.2301754,106.8069748&z=18&output=embed',
            ],
            [
                'id_site' => 'F99',
                'site' => 'FLIX SHQ',
                'buss' => 'C',
                'id_corp' => 'SAM',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Jl. Boulevard Bar. Raya No.12, RT.18/RW.19, Klp. Gading Bar., Kec. Klp. Gading, Jkt Utara, Daerah Khusus Ibukota Jakarta 14240',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1514549,106.8918949&z=12&output=embed',
            ],
            [
                'id_site' => 'M01',
                'site' => 'PIK Avenue',
                'buss' => 'M',
                'id_corp' => 'MAP',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Pantai Indah Kapuk St Boulevard, RT.6/RW.2, Kamal Muara, Penjaringan, North Jakarta City, Jakarta 14470',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1100266,106.7394165&z=15&output=embed',
            ],
            [
                'id_site' => 'M02',
                'site' => 'MOI',
                'buss' => 'M',
                'id_corp' => 'MJS',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Jl. Boulevard Bar. Raya No.12, RT.18/RW.19, Klp. Gading Bar., Kec. Klp. Gading, Jkt Utara, Daerah Khusus Ibukota Jakarta 14240',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1514549,106.8918949&z=12&output=embed',
            ],
            [
                'id_site' => 'M03',
                'site' => 'GGP',
                'buss' => 'M',
                'id_corp' => 'BJK',
                'country' => 'Jawa Barat',
                'provincy' => 'Jakarta',
                'city' => 'Bekasi Selatan',
                'address' => 'Jl. Boulevard Raya No.1, RT.003/RW.017, Jaka Setia, Kec. Bekasi Sel., Kota Bks, Jawa Barat 17147',
                'url_maps' => 'https://maps.google.com/maps?q=-6.2706285,106.9722969&z=15&output=embed',
            ],
            [
                'id_site' => 'M04',
                'site' => 'ASHTA',
                'buss' => 'M',
                'id_corp' => 'MAS',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Selatan',
                'address' => 'Jl. Senopati No.83, Senayan, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190',
                'url_maps' => 'https://maps.google.com/maps?q=-6.2301754,106.8069748&z=18&output=embed',
            ],
            [
                'id_site' => 'M05',
                'site' => 'Hublife',
                'buss' => 'M',
                'id_corp' => 'MAS',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Barat',
                'address' => 'Jl. Tanjung Duren Timur No.2, RW.5, Tj. Duren Sel., Kec. Grogol petamburan, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11470',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1803717,106.7927067&z=17&output=embed',
            ],
            [
                'id_site' => 'M06',
                'site' => 'K-Mall',
                'buss' => 'M',
                'id_corp' => 'MAS',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'Arena Pekan Raya Jkt - Kemayoran, Jl. H. Benyamin Sueb No.10, RW.10, Gn. Sahari Sel., Kec. Kemayoran, Jkt Utara, Daerah Khusus Ibukota Jakarta 14410',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1498668,106.8464893&z=15&output=embed',
            ],
            [
                'id_site' => 'O99',
                'site' => 'ASG Tower',
                'buss' => 'O',
                'id_corp' => 'MAS',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Utara',
                'address' => 'ASG Tower, Jl. Pantai Indah Kapuk No.2, RT.6/RW.2, Kamal Muara, Kec. Penjaringan, Jkt Utara, Daerah Khusus Ibukota Jakarta 14470',
                'url_maps' => 'https://maps.google.com/maps?q=-6.1100266,106.7394165&z=17&output=embed',
            ],
            [
                'id_site' => 'OD8',
                'site' => 'District 8',
                'buss' => 'O',
                'id_corp' => 'KAP',
                'country' => 'Indonesia',
                'provincy' => 'Jakarta',
                'city' => 'Jakarta Selatan',
                'address' => 'Jalan Senopati Raya No.8B, RT.5/RW.3, Senayan, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190',
                'url_maps' => 'https://maps.google.com/maps?q=-6.2304573,106.8070881&z=17&output=embed',
            ],
            [
                'id_site' => 'VAC',
                'site' => 'No SITE',
                'buss' => 'V',
                'id_corp' => 'VAC',
                'country' => 'No Country',
                'provincy' => 'No Provincy',
                'city' => 'No City',
                'address' => 'No Address',
                'url_maps' => null,
            ],
        ];

        foreach ($sites as $site) {
            Site::firstOrCreate(['id_site' => $site['id_site']], $site);
        }
    }
}
